import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth/authorization";
import { createProduct } from "../../actions";

export default async function NewProductPage() {
  await requireAdmin();
  const [brands,categories] = await Promise.all([prisma.brand.findMany({where:{active:true},orderBy:{name:"asc"}}),prisma.category.findMany({where:{active:true},orderBy:{name:"asc"}})]).catch(()=>[[],[]] as const);
  return <div><h1 className="text-3xl font-bold">New product</h1><form action={createProduct} className="mt-6 grid gap-4 rounded-xl border p-5 sm:grid-cols-2"><input name="name" required placeholder="Product name" className="rounded border px-3 py-2"/><input name="sku" required placeholder="SKU" className="rounded border px-3 py-2"/><textarea name="description" placeholder="Description" className="rounded border px-3 py-2 sm:col-span-2"/><select name="brandId" className="rounded border px-3 py-2"><option value="">No brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select name="categoryId" className="rounded border px-3 py-2"><option value="">No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input name="price" type="number" step="0.01" min="0" required placeholder="Price" className="rounded border px-3 py-2"/><input name="salePrice" type="number" step="0.01" min="0" placeholder="Sale price" className="rounded border px-3 py-2"/><input name="stock" type="number" min="0" defaultValue="0" placeholder="Stock" className="rounded border px-3 py-2"/><input name="color" placeholder="Color" className="rounded border px-3 py-2"/><input name="size" placeholder="Size" className="rounded border px-3 py-2"/><input name="imageUrl" type="url" placeholder="Image URL" className="rounded border px-3 py-2"/><select name="status" defaultValue="DRAFT" className="rounded border px-3 py-2"><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option></select><label className="flex items-center gap-2"><input name="featured" type="checkbox" value="true"/> Featured</label><button className="rounded bg-black px-4 py-2 text-white sm:col-span-2">Create product</button></form></div>;
}
